# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OFO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OFO
	
   

pod 'SWRevealViewController'    #侧边栏视图
pod 'AMap3DMap'                 #3D地图   高德备注:3D地图和2D地图不能同时使用
pod 'AMapSearch'                #搜索找车
pod 'AMapLocation'              #定位
pod 'AMapNavi'                  #导航步行规划

pod 'FTIndicator'               #提示框
pod 'swiftScan'                 #swift很好用的二维码扫描第三方库
pod 'APNumberPad'
pod 'SwiftyTimer'
pod 'SwiftySound'
pod 'AVOSCloud'                 #云接口(用于车牌号和密码)OC库需要桥接
pod 'MIBlurPopup'               #pop弹窗


  target 'OFOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OFOUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
